[package]
name = "reposyn"
version = "0.1.0"
edition = "2021"
[dependencies]
rayon = "1.10.0"
git2 = "0.20.0"
time = "0.3"
ignore = "0.4.10"
clap = { version = "4.0", features = ["derive"] }
copypasta = "0.10"
regex = "1.11.1"
globset = "0.4.15"
[dev-dependencies]
tempfile = "3.8.0"
[features]
ci-tests = []
